In [3]:
import numpy as np

In [4]:
t = np.array([1,5,6,8])

In [6]:
print(t)

[1 5 6 8]


In [7]:
x = np.array([[1,2,3],[1,2,5],[1,3,4,],[1,5,9]])

In [8]:
print(x)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [9]:
print(x.T)

[[1 1 1 1]
 [2 2 3 5]
 [3 5 4 9]]


In [10]:
xx=np.dot(x.T,x)

In [11]:
print(xx)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [15]:
xx_nv = np.linalg.inv(xx)

In [16]:
print(xx_nv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [17]:
xt= np.dot(x.T,t)

In [18]:
print(xt)

[ 20  70 124]


In [20]:
w=np.dot(xx_nv,xt)

In [21]:
print(w)

[-0.14285714  0.71428571  0.57142857]


In [23]:
import sklearn

In [47]:
from sklearn.linear_model import LinearRegression

In [37]:
model = LinearRegression()

In [38]:
x=np.array([[2,3],[2,5],[3,4],[5,9]
           ])

In [39]:
t=np.array([1,5,6,8])

In [40]:
 model.fit(x, t)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [41]:
model.score(x,t)

0.6923076923076924

In [79]:
#重回帰分析分析に使用
from sklearn.linear_model  import LinearRegression

#インスタンス化
model = LinearRegression()

# データセットの定義

x=np.array([[2,3],[2,5],[3,4],[5,9]
           ])

t=np.array([1,5,6,8])


#最適なパラメータの計算

model.fit(x, t)

#決定係数の計算

model.score(x,t)



0.6923076923076924

In [54]:
from sklearn.datasets import load_boston
boston = load_boston()

In [55]:
X = boston['data']
t = boston['target']

In [56]:
print(X)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [57]:
print(t)

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 3

In [58]:
X.shape

(506, 13)

In [59]:
t.shape

(506,)

In [64]:
from sklearn.model_selection import train_test_split

In [66]:
X_train, X_test, t_train, t_test = train_test_split(X, t, test_size=0.3, random_state=0)

In [67]:
X_train.shape

(354, 13)

In [68]:
X_test.shape

(152, 13)

In [71]:
model = LinearRegression()
model.fit(X_train,t_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [72]:
model.score(X_train,t_train)

0.7645451026942549

In [73]:
model.score(X_test,t_test)

0.6733825506400194

In [74]:
#sklearnを用いた前処理
from sklearn.preprocessing import StandardScaler
#インスタンス化
scaler = StandardScaler()
#平均と分散を計算
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [75]:
#変換
X_train_s = scaler.transform(X_train)
X_test_s = scaler.transform(X_test)

In [76]:
print(X_train_s)

[[-0.20735619 -0.49997924  1.54801583 ...  1.2272573   0.42454294
   3.10807269]
 [-0.38886492  0.34677427 -0.58974728 ...  0.05696346  0.40185312
  -0.66643035]
 [-0.33573486 -0.49997924  1.54801583 ...  1.2272573   0.39846135
   0.63936662]
 ...
 [-0.38450355 -0.49997924 -0.15303077 ... -0.30312696  0.39659002
  -0.30284441]
 [-0.37511786 -0.49997924 -0.59690657 ... -0.25811566  0.37588849
   0.89967717]
 [-0.38592298 -0.49997924 -1.00641779 ... -0.84326258  0.42454294
   0.31822262]]


In [77]:
print(X_test_s)

[[-0.39454262 -0.49997924 -1.12239824 ... -0.70822867  0.17086147
  -0.72160487]
 [ 0.70419882 -0.49997924  1.00534187 ...  0.77714428  0.0648977
  -0.41177872]
 [-0.38890688 -0.49997924  0.4025299  ... -0.93328518  0.38758427
  -0.27454978]
 ...
 [ 1.61285743 -0.49997924  1.00534187 ...  0.77714428  0.42454294
   2.59876943]
 [-0.34350332 -0.49997924 -0.1687812  ... -0.03305915  0.42454294
  -1.11772962]
 [-0.39902507 -0.49997924 -1.27417512 ...  0.10197476  0.39202867
  -1.02294263]]
